# gitops/base/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mario-service
spec:
  type: ClusterIP   # IMPORTANT: Must be ClusterIP when using Istio + Flagger
  selector:
    app: mario
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http