# gitops/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

bases:
  - ../../base

images:
  - name: 145689194429.dkr.ecr.us-west-2.amazonaws.com/mario
    newTag: dev-latest

replicas:
  - name: mario-deployment
    count: 1

configMapGenerator:
  - name: mario-config
    behavior: merge
    literals:
      - ENVIRONMENT=dev