# gitops/overlays/production/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base
  - canary.yaml

patchesStrategicMerge:
  - deployment-patch.yaml

images:
  - name: mario-game
    newTag: v1.2.0

replicas:
  - name: mario-deployment
    count: 1

configMapGenerator:
  - name: mario-config
    behavior: merge
    literals:
      - ENVIRONMENT=production
