# gitops/overlays/production/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml

images:
  - name: mario-game
    newTag: v1.1.0  # Immutable tag

replicas:
  - name: mario-deployment
    count: 3

configMapGenerator:
  - name: mario-config
    behavior: merge
    literals:
      - ENVIRONMENT=production